<!DOCTYPE html>
<html lang="en"><head>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-html/tabby.min.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-b6e6edf6cb1293d7f667c2f39c143ab5.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">
<meta name="author" content="Dr.&nbsp;Mine Çetinkaya-Rundel">
<meta name="dcterms.date" content="2025-11-18">
<title>STA 199 – Exam 2 review</title>
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
<link rel="stylesheet" href="../site_libs/revealjs/dist/reset.css">
<link rel="stylesheet" href="../site_libs/revealjs/dist/reveal.css">
<style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #767676;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #767676;  padding-left: 4px; }
    div.sourceCode
      { color: #545454; background-color: #fefefe; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #545454; } /* Normal */
    code span.al { color: #7928a1; } /* Alert */
    code span.an { color: #696969; } /* Annotation */
    code span.at { color: #a55a00; } /* Attribute */
    code span.bn { color: #7928a1; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #d91e18; } /* ControlFlow */
    code span.ch { color: #008000; } /* Char */
    code span.cn { color: #d91e18; } /* Constant */
    code span.co { color: #696969; } /* Comment */
    code span.cv { color: #696969; font-style: italic; } /* CommentVar */
    code span.do { color: #696969; font-style: italic; } /* Documentation */
    code span.dt { color: #7928a1; } /* DataType */
    code span.dv { color: #7928a1; } /* DecVal */
    code span.er { color: #7928a1; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #a55a00; } /* Float */
    code span.fu { color: #06287e; } /* Function */
    code span.im { } /* Import */
    code span.in { color: #696969; } /* Information */
    code span.kw { color: #d91e18; } /* Keyword */
    code span.op { color: #00769e; } /* Operator */
    code span.ot { color: #d91e18; } /* Other */
    code span.pp { color: #7928a1; } /* Preprocessor */
    code span.sc { color: #00769e; } /* SpecialChar */
    code span.ss { color: #008000; } /* SpecialString */
    code span.st { color: #008000; } /* String */
    code span.va { color: #a55a00; } /* Variable */
    code span.vs { color: #008000; } /* VerbatimString */
    code span.wa { color: #696969; font-style: italic; } /* Warning */
  </style>
<link rel="stylesheet" href="../site_libs/revealjs/dist/theme/quarto-27130b92cf5bfca8d85a2a871b9fcd62.css">
<link href="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
<link href="../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
<link href="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
<link href="../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
<style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
<meta property="og:title" content="Exam 2 review – STA 199">
<meta property="og:description" content="Lecture 23">
<meta property="og:site_name" content="STA 199">
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center"><h1 class="title">Exam 2 review</h1>
  <p class="subtitle">Lecture 23</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Dr.&nbsp;Mine Çetinkaya-Rundel 
</div>
        <p class="quarto-title-affiliation">
            Duke University <br> STA 199 - Fall 2025
          </p>
    </div>
</div>

  <p class="date">November 18, 2025</p>
</section><section><section id="warm-up" class="title-slide slide level1 center"><h1>Warm-up</h1>

</section><section id="announcements" class="slide level2 smaller"><h2>Announcements</h2>
<ul>
<li>
<p>Exam - In class:</p>
<ul>
<li>Cheat sheet: 8.5x11, both sides, hand written or typed, any content you want, must be prepared by you</li>
<li>Bring a pencil and eraser (you’re allowed to use a pen, but you might not want to)</li>
</ul>
</li>
<li>
<p>Exam - Take home:</p>
<ul>
<li>Open book, notes, internet</li>
<li>No office hours</li>
<li>Questions on Ed (private by default)</li>
<li>Due Saturday, November 22 at noon</li>
</ul>
</li>
<li><p>Reminder: Academic dishonesty / Duke Community Standard</p></li>
<li><p>Next Tuesday: Can watch class live on Panopto link</p></li>
</ul></section><section id="from-last-class-ae-14-chicago-taxi-classification" class="slide level2 smaller"><h2>From last class: ae-14-chicago-taxi-classification</h2>
<div class="appex">
<p>Finish up the application exercise by finding the area under the ROC curve.</p>
</div>
</section><section id="recap" class="slide level2 xsmall"><h2>Recap</h2>
<ul>
<li class="fragment"><p>Split data into training and testing sets (generally 75/25)</p></li>
<li class="fragment"><p>Fit models on training data and reduce to a few candidate models</p></li>
<li class="fragment"><p>Make predictions on testing data</p></li>
<li class="fragment">
<p>Evaluate predictions on testing data using appropriate predictive performance metrics</p>
<ul>
<li class="fragment">Linear models: Adjusted R-squared, AIC, etc.</li>
<li class="fragment">Logistic models: False negative and positive rates, AUC (area under the curve), etc.</li>
</ul>
</li>
<li class="fragment"><p>Don’t forget to also consider explainability and domain knowledge when selecting a final model</p></li>
<li class="fragment"><p>In a future machine learning course: Cross-validation (partitioning training data into training and validation sets and repeating this many times to evaluate model predictive performance before using the testing data), feature engineering, hyperparameter tuning, more complex models (random forests, gradient boosting machines, neural networks, etc.)</p></li>
</ul></section></section><section><section id="modeling-review" class="title-slide slide level1 center"><h1>Modeling review</h1>

</section><section id="hotel-cancellations" class="slide level2"><h2>Hotel cancellations</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a></a><span class="fu">library</span>(tidymodels)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a></a>hotels <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/hotels.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section><section id="data-prep" class="slide level2 smaller"><h2>Data prep</h2>
<ul>
<li>Relevel <code>is_canceled</code>
</li>
<li>Remove bookings with average daily rate greater than $1,000</li>
<li>Remove bookings with number of adults greater than or equal to 5</li>
<li>Split the data into a training set (75%) and a testing set (25%)</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb3" data-code-line-numbers="|2-5|6|1|8-11"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a></a>hotels <span class="ot">&lt;-</span> hotels <span class="sc">|&gt;</span></span>
<span id="cb3-2"><a></a>  <span class="fu">mutate</span>(</span>
<span id="cb3-3"><a></a>    <span class="at">is_canceled =</span> <span class="fu">if_else</span>(is_canceled <span class="sc">==</span> <span class="dv">1</span>, <span class="st">"canceled"</span>, <span class="st">"not canceled"</span>),</span>
<span id="cb3-4"><a></a>    <span class="at">is_canceled =</span> <span class="fu">fct_relevel</span>(is_canceled, <span class="st">"not canceled"</span>, <span class="st">"canceled"</span>)</span>
<span id="cb3-5"><a></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb3-6"><a></a>  <span class="fu">filter</span>(adr <span class="sc">&lt;=</span> <span class="dv">1000</span>, adults <span class="sc">&lt;</span> <span class="dv">5</span>)</span>
<span id="cb3-7"><a></a></span>
<span id="cb3-8"><a></a><span class="fu">set.seed</span>(<span class="dv">1117</span>)</span>
<span id="cb3-9"><a></a>hotels_split <span class="ot">&lt;-</span> <span class="fu">initial_split</span>(hotels)</span>
<span id="cb3-10"><a></a>hotels_train <span class="ot">&lt;-</span> <span class="fu">training</span>(hotels_split)</span>
<span id="cb3-11"><a></a>hotels_test <span class="ot">&lt;-</span> <span class="fu">testing</span>(hotels_split)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section><section id="participate" class="slide level2 xsmall"><h2>Participate 📱💻</h2>
<div class="columns">
<div class="column" style="width:70%;">
<div class="wooclap">
<p>What type of model would you use to answer the question:</p>
<blockquote>
<p>Are reservations earlier in the month or later in the month more likely to be cancelled?</p>
</blockquote>
<div class="wooclap-choices">
<ul>
<li>Linear regression with a numerical predictor</li>
<li>Linear regression with a categorical predictor</li>
<li>Linear regression with a log-transformed outcome and a numerical predictor</li>
<li>Linear regression with a log-transformed outcome and a categorical predictor</li>
<li>Logistic regression with a numerical predictor <span class="fragment">✅</span>
</li>
<li>Logistic regression with a categorical predictor</li>
</ul>
</div>
</div>
</div><div class="column" style="width:30%;">
<div class="quarto-figure quarto-figure-center">
<figure><p><img data-src="images/wooclap-qr.png" class="quarto-figure quarto-figure-center" width="200"></p>
</figure>
</div>
<div class="small">
<p>Scan the QR code or go to <a href="https://app.wooclap.com/sta199">app.wooclap.com/sta199</a>. Log in with your Duke NetID.</p>
</div>
</div></div>
</section><section id="linear-regression" class="slide level2"><h2>Linear regression</h2>
<p>Numerical outcome:</p>
<p><span class="math display">\[
y = \beta_0 + \beta_1 x_1 + \beta_2 x_2 + \cdots + \beta_k x_k + \varepsilon
\]</span></p>
<p><br></p>
<p><span class="math display">\[
\widehat{y} = b_0 + b_1 x_1 + b_2 x_2 + \cdots + b_k x_k
\]</span></p>
</section><section id="linear-regression-with-log-transformed-outcome" class="slide level2"><h2>Linear regression with log-transformed outcome</h2>
<p>Numerical outcome, log-transformed for a better linear fit:</p>
<p><span class="math display">\[
log(y) = \beta_0 + \beta_1 x_1 + \beta_2 x_2 + \cdots + \beta_k x_k + \varepsilon
\]</span></p>
<p><br></p>
<p><span class="math display">\[
log(\widehat{y}) = b_0 + b_1 x_1 + b_2 x_2 + \cdots + b_k x_k
\]</span></p>
</section><section id="logistic-regression" class="slide level2"><h2>Logistic regression</h2>
<p>Binary outcome, where <span class="math inline">\(p = P(Y=1)\)</span>, the probability of success:</p>
<p><span class="math display">\[
\log\left(\frac{p}{1-p}\right) = \beta_0 + \beta_1 x_1 + \beta_2 x_2 + \cdots + \beta_k x_k + \varepsilon
\]</span></p>
<p><br></p>
<p><span class="math display">\[
\log\left(\frac{\widehat{p}}{1-\widehat{p}}\right) = b_0 + b_1 x_1 + b_2 x_2 + \cdots + b_k x_k
\]</span></p>
</section><section id="cancellation-arrival-date" class="slide level2 smaller"><h2>Cancellation ~ arrival date</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a></a>is_canceled_fit_1 <span class="ot">&lt;-</span> <span class="fu">logistic_reg</span>() <span class="sc">|&gt;</span></span>
<span id="cb4-2"><a></a>  <span class="fu">fit</span>(is_canceled <span class="sc">~</span> arrival_date_day_of_month, <span class="at">data =</span> hotels_train)</span>
<span id="cb4-3"><a></a></span>
<span id="cb4-4"><a></a><span class="fu">tidy</span>(is_canceled_fit_1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 5
  term                      estimate std.error statistic   p.value
  &lt;chr&gt;                        &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept)               -0.510    0.0142      -35.8  1.80e-280
2 arrival_date_day_of_month -0.00152  0.000789     -1.93 5.41e-  2</code></pre>
</div>
</div>
</section><section id="slope-in-logistic-regression" class="slide level2 smaller"><h2>Slope in logistic regression</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a></a><span class="fu">tidy</span>(is_canceled_fit_1) <span class="sc">|&gt;</span></span>
<span id="cb6-2"><a></a>  <span class="fu">select</span>(term, estimate) <span class="sc">|&gt;</span></span>
<span id="cb6-3"><a></a>  <span class="fu">mutate</span>(<span class="at">exp_estimate =</span> <span class="fu">exp</span>(estimate))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 3
  term                      estimate exp_estimate
  &lt;chr&gt;                        &lt;dbl&gt;        &lt;dbl&gt;
1 (Intercept)               -0.510          0.601
2 arrival_date_day_of_month -0.00152        0.998</code></pre>
</div>
</div>
<div class="fragment">
<p><br></p>
<p>For each day the booking is later in the month, the odds of reservations being canceled is predicted to be lower by a factor of 0.998, on average.</p>
</div>
</section><section id="intercept-in-logistic-regression" class="slide level2 smaller"><h2>Intercept in logistic regression</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a></a><span class="fu">tidy</span>(is_canceled_fit_1) <span class="sc">|&gt;</span></span>
<span id="cb8-2"><a></a>  <span class="fu">select</span>(term, estimate) <span class="sc">|&gt;</span></span>
<span id="cb8-3"><a></a>  <span class="fu">mutate</span>(<span class="at">exp_estimate =</span> <span class="fu">exp</span>(estimate))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 3
  term                      estimate exp_estimate
  &lt;chr&gt;                        &lt;dbl&gt;        &lt;dbl&gt;
1 (Intercept)               -0.510          0.601
2 arrival_date_day_of_month -0.00152        0.998</code></pre>
</div>
</div>
<div class="fragment">
<p><br></p>
<p>On the 0th day of the month, the odds of reservations being canceled is predicted to be 0.601, on average. The intercept is not meaningful in this context since there is no 0th day of the month.</p>
</div>
</section><section id="prediction-in-logistic-regression" class="slide level2 smaller"><h2>Prediction in logistic regression</h2>
<div class="task">
<p>Predict the probability of cancellation for a booking made on the 18th day of the month.</p>
</div>
<div class="fragment">
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a></a>new_booking <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">arrival_date_day_of_month =</span> <span class="dv">18</span>)</span>
<span id="cb10-2"><a></a><span class="fu">augment</span>(is_canceled_fit_1, <span class="at">new_data =</span> new_booking)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 4
  .pred_class  `.pred_not canceled` .pred_canceled
  &lt;fct&gt;                       &lt;dbl&gt;          &lt;dbl&gt;
1 not canceled                0.631          0.369
# ℹ 1 more variable: arrival_date_day_of_month &lt;dbl&gt;</code></pre>
</div>
</div>
</div>
</section><section id="augment-vs.-predict" class="slide level2 smaller"><h2>
<code>augment()</code> vs.&nbsp;<code>predict()</code>
</h2>
<ul>
<li>
<code>augment()</code> returns the data frame passed to <code>new_data</code> _augment_ed by
<ul>
<li>the predicted probability of success,</li>
<li>the predicted probability of failure, and</li>
<li>the predicted class (based on a 0.5 cutoff by default)</li>
</ul>
</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a></a><span class="fu">augment</span>(is_canceled_fit_1, <span class="at">new_data =</span> new_booking)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 4
  .pred_class  `.pred_not canceled` .pred_canceled
  &lt;fct&gt;                       &lt;dbl&gt;          &lt;dbl&gt;
1 not canceled                0.631          0.369
# ℹ 1 more variable: arrival_date_day_of_month &lt;dbl&gt;</code></pre>
</div>
</div>
<div class="fragment">
<ul>
<li>
<code><a href="https://rdrr.io/r/stats/predict.html">predict()</a></code> the predicted class (based on a 0.5 cutoff by default)</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a></a><span class="fu">predict</span>(is_canceled_fit_1, <span class="at">new_data =</span> new_booking)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
  .pred_class 
  &lt;fct&gt;       
1 not canceled</code></pre>
</div>
</div>
</div>
</section><section id="cancellation-arrival-date-hotel-type" class="slide level2 smaller"><h2>Cancellation ~ arrival date + hotel type</h2>
<div class="task">
<p>Fit another model to predict whether a reservation was cancelled from <code>arrival_date_day_of_month</code> and <code>hotel</code> type (Resort or City Hotel), allowing the relationship between <code>arrival_date_day_of_month</code> and <code>is_canceled</code> to <strong>not</strong> vary based on <code>hotel</code> type.</p>
</div>
<div class="fragment">
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a></a>is_canceled_fit_2 <span class="ot">&lt;-</span> <span class="fu">logistic_reg</span>() <span class="sc">|&gt;</span></span>
<span id="cb16-2"><a></a>  <span class="fu">fit</span>(is_canceled <span class="sc">~</span> arrival_date_day_of_month <span class="sc">+</span> hotel, <span class="at">data =</span> hotels_train)</span>
<span id="cb16-3"><a></a></span>
<span id="cb16-4"><a></a><span class="fu">tidy</span>(is_canceled_fit_2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 5
  term                      estimate std.error statistic  p.value
  &lt;chr&gt;                        &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
1 (Intercept)               -0.315    0.0151      -20.9  3.46e-97
2 arrival_date_day_of_month -0.00155  0.000797     -1.94 5.18e- 2
3 hotelResort Hotel         -0.614    0.0153      -40.0  0       </code></pre>
</div>
</div>
</div>
</section><section id="slope-in-logistic-regression-1" class="slide level2 smaller"><h2>Slope in logistic regression</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a></a><span class="fu">tidy</span>(is_canceled_fit_2) <span class="sc">|&gt;</span></span>
<span id="cb18-2"><a></a>  <span class="fu">select</span>(term, estimate) <span class="sc">|&gt;</span></span>
<span id="cb18-3"><a></a>  <span class="fu">mutate</span>(<span class="at">exp_estimate =</span> <span class="fu">exp</span>(estimate))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 3
  term                      estimate exp_estimate
  &lt;chr&gt;                        &lt;dbl&gt;        &lt;dbl&gt;
1 (Intercept)               -0.315          0.729
2 arrival_date_day_of_month -0.00155        0.998
3 hotelResort Hotel         -0.614          0.541</code></pre>
</div>
</div>
<div class="fragment">
<p><br></p>
<p>Holding hotel type constant, for each day the booking is later in the month, the odds of reservations being canceled is predicted to be lower by a factor of 0.998, on average.</p>
</div>
</section><section id="slope-in-logistic-regression-2" class="slide level2 smaller"><h2>Slope in logistic regression</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a></a><span class="fu">tidy</span>(is_canceled_fit_2) <span class="sc">|&gt;</span></span>
<span id="cb20-2"><a></a>  <span class="fu">select</span>(term, estimate) <span class="sc">|&gt;</span></span>
<span id="cb20-3"><a></a>  <span class="fu">mutate</span>(<span class="at">exp_estimate =</span> <span class="fu">exp</span>(estimate))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 3
  term                      estimate exp_estimate
  &lt;chr&gt;                        &lt;dbl&gt;        &lt;dbl&gt;
1 (Intercept)               -0.315          0.729
2 arrival_date_day_of_month -0.00155        0.998
3 hotelResort Hotel         -0.614          0.541</code></pre>
</div>
</div>
<div class="fragment">
<p><br></p>
<p>Holding arrival day of month constant, the odds of Resort Hotel reservations being canceled is predicted to be lower by a factor of 0.541 compared to City Hotel reservations, on average.</p>
</div>
</section><section id="intercept-in-logistic-regression-1" class="slide level2 smaller"><h2>Intercept in logistic regression</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a></a><span class="fu">tidy</span>(is_canceled_fit_2) <span class="sc">|&gt;</span></span>
<span id="cb22-2"><a></a>  <span class="fu">select</span>(term, estimate) <span class="sc">|&gt;</span></span>
<span id="cb22-3"><a></a>  <span class="fu">mutate</span>(<span class="at">exp_estimate =</span> <span class="fu">exp</span>(estimate))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 3
  term                      estimate exp_estimate
  &lt;chr&gt;                        &lt;dbl&gt;        &lt;dbl&gt;
1 (Intercept)               -0.315          0.729
2 arrival_date_day_of_month -0.00155        0.998
3 hotelResort Hotel         -0.614          0.541</code></pre>
</div>
</div>
<div class="fragment">
<p><br></p>
<p>On the 0th day of the month, the odds of City Hotel reservations being canceled is predicted to be 0.729, on average. The intercept is not meaningful in this context since there is no 0th day of the month.</p>
</div>
</section><section id="cancellation-arrival-date-hotel-type-1" class="slide level2 smaller"><h2>Cancellation ~ arrival date * hotel type</h2>
<div class="task">
<p>Fit another model to predict whether a reservation was cancelled from <code>arrival_date_day_of_month</code> and <code>hotel</code> type (Resort or City Hotel), allowing the relationship between <code>arrival_date_day_of_month</code> and <code>is_canceled</code> to vary based on <code>hotel</code> type.</p>
</div>
<div class="fragment">
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a></a>is_canceled_fit_3 <span class="ot">&lt;-</span> <span class="fu">logistic_reg</span>() <span class="sc">|&gt;</span></span>
<span id="cb24-2"><a></a>  <span class="fu">fit</span>(is_canceled <span class="sc">~</span> arrival_date_day_of_month <span class="sc">*</span> hotel, <span class="at">data =</span> hotels_train)</span>
<span id="cb24-3"><a></a></span>
<span id="cb24-4"><a></a><span class="fu">tidy</span>(is_canceled_fit_3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 5
  term                           estimate std.error statistic  p.value
  &lt;chr&gt;                             &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
1 (Intercept)                    -0.321    0.0172     -18.7   6.73e-78
2 arrival_date_day_of_month      -0.00117  0.000954    -1.23  2.19e- 1
3 hotelResort Hotel              -0.594    0.0313     -19.0   3.50e-80
4 arrival_date_day_of_month:hot… -0.00125  0.00174     -0.719 4.72e- 1</code></pre>
</div>
</div>
</div>
</section><section id="logistic-regression-w-interaction-effect" class="slide level2 smaller"><h2>Logistic regression w/ interaction effect</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a></a><span class="fu">tidy</span>(is_canceled_fit_3) <span class="sc">|&gt;</span></span>
<span id="cb26-2"><a></a>  <span class="fu">select</span>(term, estimate)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 2
  term                                        estimate
  &lt;chr&gt;                                          &lt;dbl&gt;
1 (Intercept)                                 -0.321  
2 arrival_date_day_of_month                   -0.00117
3 hotelResort Hotel                           -0.594  
4 arrival_date_day_of_month:hotelResort Hotel -0.00125</code></pre>
</div>
</div>
<p><br></p>
<div class="fragment">
<p><span class="math display">\[
\begin{aligned}
\log\left(\frac{\widehat{p}}{1-\widehat{p}}\right) &amp;= -0.321 \\
&amp;- 0.00117 \times \texttt{arrival_date_day_of_month} \\
&amp;- 0.594 \times \texttt{hotelResort Hotel} \\
&amp;- 0.00125 \times \texttt{arrival_date_day_of_month:hotelResort Hotel} \\
\end{aligned}
\]</span></p>
</div>
</section><section id="logistic-regression-w-interaction-effect-1" class="slide level2 smaller scrollable"><h2>Logistic regression w/ interaction effect</h2>
<p><span class="math display">\[
\begin{aligned}
\log\left(\frac{\widehat{p}}{1-\widehat{p}}\right) &amp;= -0.321 \\
&amp;- 0.00117 \times \texttt{arrival_date_day_of_month} \\
&amp;- 0.594 \times \texttt{hotelResort Hotel} \\
&amp;- 0.00125 \times \texttt{arrival_date_day_of_month:hotelResort Hotel} \\
\end{aligned}
\]</span></p>
<p><br></p>
<div class="fragment">
<p><strong>City Hotel:</strong></p>
<p><span class="math display">\[
\begin{aligned}
\log\left(\frac{\widehat{p}}{1-\widehat{p}}\right) &amp;= -0.321 \\
&amp;- 0.00117 \times \texttt{arrival_date_day_of_month} \\
&amp;- 0.594 \times 0 \\
&amp;- 0.00125 \times \texttt{arrival_date_day_of_month} \times 0 \\
\\
&amp;= -0.321 - 0.00117 \times \texttt{arrival_date_day_of_month} \\
\end{aligned}
\]</span></p>
</div>
</section><section id="logistic-regression-w-interaction-effect-2" class="slide level2 smaller scrollable"><h2>Logistic regression w/ interaction effect</h2>
<p><span class="math display">\[
\begin{aligned}
\log\left(\frac{\widehat{p}}{1-\widehat{p}}\right) &amp;= -0.321 \\
&amp;- 0.00117 \times \texttt{arrival_date_day_of_month} \\
&amp;- 0.594 \times \texttt{hotelResort Hotel} \\
&amp;- 0.00125 \times \texttt{arrival_date_day_of_month:hotelResort Hotel} \\
\end{aligned}
\]</span></p>
<p><br></p>
<div class="fragment">
<p><strong>Resort Hotel:</strong></p>
<p><span class="math display">\[
\begin{aligned}
\log\left(\frac{\widehat{p}}{1-\widehat{p}}\right) &amp;= -0.321 \\
&amp;- 0.00117 \times \texttt{arrival_date_day_of_month} \\
&amp;- 0.594 \times 1 \\
&amp;- 0.00125 \times \texttt{arrival_date_day_of_month} \times 1 \\
\\
&amp;= -(0.321+0.594) - (0.00117+0.00125) \times \texttt{arrival_date_day_of_month} \\
\\
&amp;= -0.915 - 0.00242 \times \texttt{arrival_date_day_of_month} \\
\end{aligned}
\]</span></p>
</div>
</section><section id="logistic-regression-w-interaction-effect-3" class="slide level2 smaller"><h2>Logistic regression w/ interaction effect</h2>
<p><strong>City Hotel:</strong></p>
<p><span class="math display">\[
\log\left(\frac{\widehat{p}}{1-\widehat{p}}\right) = -0.321 - 0.00117 \times \texttt{arrival_date_day_of_month}
\]</span></p>
<ul>
<li><p><code>exp(-0.00117)</code> = 0.999: In City Hotels, for each day the booking is later in the month, the odds of reservations being canceled is predicted to be lower by a factor of 0.999, on average.</p></li>
<li><p><code>exp(−0.321)</code> = 0.725: In City Hotels, on the 0th day of the month, the odds of reservations being canceled is predicted to be 0.725, on average. The intercept is not meaningful in this context since there is no 0th day of the month.</p></li>
</ul></section><section id="logistic-regression-w-interaction-effect-4" class="slide level2 smaller"><h2>Logistic regression w/ interaction effect</h2>
<p><strong>Resort Hotel:</strong></p>
<p><span class="math display">\[
\log\left(\frac{\widehat{p}}{1-\widehat{p}}\right) = -0.915 - 0.00242 \times \texttt{arrival_date_day_of_month}
\]</span></p>
<ul>
<li><p><code>exp(-0.00117)</code> = 0.998: In Resort Hotels, for each day the booking is later in the month, the odds of reservations being canceled is predicted to be lower by a factor of 0.998, on average.</p></li>
<li><p><code>exp(−0.321)</code> = 0.401: In Resort Hotels, on the 0th day of the month, the odds of reservations being canceled is predicted to be 0.401, on average. The intercept is not meaningful in this context since there is no 0th day of the month.</p></li>
</ul></section><section id="participate-1" class="slide level2 xsmall"><h2>Participate 📱💻</h2>
<div class="columns">
<div class="column" style="width:70%;">
<div class="wooclap">
<p>Suppose we want to select a final model to predict whether a reservation was cancelled. Which metric would be most appropriate to evaluate the predictive performance of our logistic regression models?</p>
<div class="wooclap-choices">
<ul>
<li>True positive rate</li>
<li>Area under the ROC curve <span class="fragment">✅</span>
</li>
<li>Adjusted R-squared</li>
<li>Root mean squared error</li>
<li>R-squared</li>
</ul>
</div>
</div>
</div><div class="column" style="width:30%;">
<div class="quarto-figure quarto-figure-center">
<figure><p><img data-src="images/wooclap-qr.png" class="quarto-figure quarto-figure-center" width="200"></p>
</figure>
</div>
<div class="small">
<p>Scan the QR code or go to <a href="https://app.wooclap.com/sta199">app.wooclap.com/sta199</a>. Log in with your Duke NetID.</p>
</div>
</div></div>
</section><section id="area-under-the-roc-curve-auc" class="slide level2 xsmall"><h2>Area under the ROC curve (AUC)</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a></a>is_canceled_aug_1 <span class="ot">&lt;-</span> <span class="fu">augment</span>(is_canceled_fit_1, <span class="at">new_data =</span> hotels_test)</span>
<span id="cb28-2"><a></a>is_canceled_aug_2 <span class="ot">&lt;-</span> <span class="fu">augment</span>(is_canceled_fit_2, <span class="at">new_data =</span> hotels_test)</span>
<span id="cb28-3"><a></a>is_canceled_aug_3 <span class="ot">&lt;-</span> <span class="fu">augment</span>(is_canceled_fit_3, <span class="at">new_data =</span> hotels_test)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="columns">
<div class="column fragment" style="width:33%;">
<p>Single predictor:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a></a><span class="fu">roc_auc</span>(</span>
<span id="cb29-2"><a></a>  is_canceled_aug_1,</span>
<span id="cb29-3"><a></a>  <span class="at">truth =</span> is_canceled,</span>
<span id="cb29-4"><a></a>  .pred_canceled,</span>
<span id="cb29-5"><a></a>  <span class="at">event_level =</span> <span class="st">"second"</span></span>
<span id="cb29-6"><a></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
  .metric .estimator .estimate
  &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt;
1 roc_auc binary         0.503</code></pre>
</div>
</div>
</div><div class="column fragment" style="width:33%;">
<p>Main effects:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a></a><span class="fu">roc_auc</span>(</span>
<span id="cb31-2"><a></a>  is_canceled_aug_2,</span>
<span id="cb31-3"><a></a>  <span class="at">truth =</span> is_canceled,</span>
<span id="cb31-4"><a></a>  .pred_canceled,</span>
<span id="cb31-5"><a></a>  <span class="at">event_level =</span> <span class="st">"second"</span></span>
<span id="cb31-6"><a></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
  .metric .estimator .estimate
  &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt;
1 roc_auc binary         0.571</code></pre>
</div>
</div>
</div><div class="column fragment" style="width:33%;">
<p>Interaction effects:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a></a><span class="fu">roc_auc</span>(</span>
<span id="cb33-2"><a></a>  is_canceled_aug_3,</span>
<span id="cb33-3"><a></a>  <span class="at">truth =</span> is_canceled,</span>
<span id="cb33-4"><a></a>  .pred_canceled,</span>
<span id="cb33-5"><a></a>  <span class="at">event_level =</span> <span class="st">"second"</span></span>
<span id="cb33-6"><a></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
  .metric .estimator .estimate
  &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt;
1 roc_auc binary         0.571</code></pre>
</div>
</div>
</div></div>
<div class="task fragment">
<p>Which model would you select as your final model based on AUC?</p>
</div>
</section><section id="linear-regression-1" class="slide level2"><h2>Linear regression</h2>
<p>The dataset also contains information about the average daily rate (<code>adr</code>) for each reservation. The following model predicts <code>adr</code> from <code>adults</code> and <code>hotel</code> type.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 5
  term              estimate std.error statistic   p.value
  &lt;chr&gt;                &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept)           50.5     0.605      83.5 0        
2 adults                29.5     0.311      94.9 0        
3 hotelResort Hotel    -10.7     0.322     -33.1 2.48e-239</code></pre>
</div>
</div>
</section><section id="participate-2" class="slide level2 xsmall"><h2>Participate 📱💻</h2>
<div class="columns">
<div class="column" style="width:70%;">
<div class="wooclap">
<p>Which of the following is the best interpretation of the slope coefficient for <code>adults</code>?</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 5
  term              estimate std.error statistic   p.value
  &lt;chr&gt;                &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept)           50.5     0.605      83.5 0        
2 adults                29.5     0.311      94.9 0        
3 hotelResort Hotel    -10.7     0.322     -33.1 2.48e-239</code></pre>
</div>
</div>
<p>For each additional adult in the booking, the average daily rate is predicted to be higher by $29.50</p>
<div class="wooclap-choices">
<ul>
<li>on average, holding hotel type constant. <span class="fragment">✅</span>
</li>
<li>for Resort Hotels compared to City Hotels, on average.</li>
<li>for City Hotels compared to Resort Hotels, on average.</li>
<li>on average, not holding any other variables constant.</li>
</ul>
</div>
</div>
</div><div class="column" style="width:30%;">
<div class="quarto-figure quarto-figure-center">
<figure><p><img data-src="images/wooclap-qr.png" class="quarto-figure quarto-figure-center" width="200"></p>
</figure>
</div>
<div class="small">
<p>Scan the QR code or go to <a href="https://app.wooclap.com/sta199">app.wooclap.com/sta199</a>. Log in with your Duke NetID.</p>
</div>
</div></div>
</section><section id="participate-3" class="slide level2 xsmall"><h2>Participate 📱💻</h2>
<div class="columns">
<div class="column" style="width:70%;">
<div class="wooclap medium">
<p>Which of the following is the correct interpretation of the slope coefficient for <code>hotel</code>?</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 5
  term              estimate std.error statistic   p.value
  &lt;chr&gt;                &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept)           50.5     0.605      83.5 0        
2 adults                29.5     0.311      94.9 0        
3 hotelResort Hotel    -10.7     0.322     -33.1 2.48e-239</code></pre>
</div>
</div>
<div class="wooclap-choices">
<ul>
<li>For each additional Resort Hotel booking, the predicted average daily rate is $10.70 lower, holding number of adults constant.</li>
<li>For each additional adult in the booking, the average daily rate is predicted to be lower by $10.70 for resort hotels compared to City Hotels, on average.</li>
<li>Resort Hotels bookings are predicted to have an average daily rate that is $10.70 lower than City Hotels, on average, holding number of adults constant. <span class="fragment">✅</span>
</li>
<li>Resort Hotels bookings are predicted to have an average daily rate that is $10.70 higher than City Hotels, on average, holding number of adults constant.</li>
</ul>
</div>
</div>
</div><div class="column" style="width:30%;">
<div class="quarto-figure quarto-figure-center">
<figure><p><img data-src="images/wooclap-qr.png" class="quarto-figure quarto-figure-center" width="200"></p>
</figure>
</div>
<div class="small">
<p>Scan the QR code or go to <a href="https://app.wooclap.com/sta199">app.wooclap.com/sta199</a>. Log in with your Duke NetID.</p>
</div>
</div></div>
</section><section id="participate-4" class="slide level2 xsmall"><h2>Participate 📱💻</h2>
<div class="columns">
<div class="column" style="width:70%;">
<div class="wooclap">
<p>Which of the following is the correct interpretation of the intercept?</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 5
  term              estimate std.error statistic   p.value
  &lt;chr&gt;                &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept)           50.5     0.605      83.5 0        
2 adults                29.5     0.311      94.9 0        
3 hotelResort Hotel    -10.7     0.322     -33.1 2.48e-239</code></pre>
</div>
</div>
<div class="wooclap-choices">
<ul>
<li>The predicted average daily rate for a bookings with 0 adults at a Resort Hotel is $50.50, on average.</li>
<li>The predicted average daily rate for a bookings with 0 adults at a City Hotel is $50.50, on average. <span class="fragment">✅</span>
</li>
<li>For each additional adult and Resort Hotel in the booking, the average daily rate is predicted to be $50.50 higher, on average.</li>
<li>For each additional adult and City Hotel in the booking, the average daily rate is predicted to be $50.50 higher, on average.</li>
</ul>
</div>
</div>
</div><div class="column" style="width:30%;">
<div class="quarto-figure quarto-figure-center">
<figure><p><img data-src="images/wooclap-qr.png" class="quarto-figure quarto-figure-center" width="200"></p>
</figure>
</div>
<div class="small">
<p>Scan the QR code or go to <a href="https://app.wooclap.com/sta199">app.wooclap.com/sta199</a>. Log in with your Duke NetID.</p>
</div>
</div></div>
</section><section id="participate-5" class="slide level2 xsmall"><h2>Participate 📱💻</h2>
<div class="columns">
<div class="column" style="width:70%;">
<div class="wooclap">
<p>Which of the following (Plot A or Plot B) is the correct visual representation of this model?</p>
<div class="cell quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img data-src="23-exam-2-review_files/figure-revealjs/unnamed-chunk-25-1.png" width="480"></p>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img data-src="23-exam-2-review_files/figure-revealjs/unnamed-chunk-25-2.png" width="480"></p>
</div>
</div>
</div>
<div class="wooclap-choices">
<ul>
<li>Plot A</li>
<li>Plot B <span class="fragment">✅</span>
</li>
</ul>
</div>
</div>
</div><div class="column" style="width:30%;">
<div class="quarto-figure quarto-figure-center">
<figure><p><img data-src="images/wooclap-qr.png" class="quarto-figure quarto-figure-center" width="200"></p>
</figure>
</div>
<div class="small">
<p>Scan the QR code or go to <a href="https://app.wooclap.com/sta199">app.wooclap.com/sta199</a>. Log in with your Duke NetID.</p>
</div>
</div></div>


</section></section>
</div>
  <div class="quarto-auto-generated-content" style="display: none;">
<p><img src="images/logo.png" class="slide-logo"></p>
<div class="footer footer-default">
<p><a href="https://sta199-f25.github.io/">🔗 sta199-f25.github.io</a></p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="../site_libs/revealjs/dist/reveal.js"></script><!-- reveal.js plugins --><script src="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script><script src="../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script><script src="../site_libs/revealjs/plugin/reveal-menu/menu.js"></script><script src="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script><script src="../site_libs/revealjs/plugin/quarto-support/support.js"></script><script src="../site_libs/revealjs/plugin/notes/notes.js"></script><script src="../site_libs/revealjs/plugin/search/search.js"></script><script src="../site_libs/revealjs/plugin/zoom/zoom.js"></script><script src="../site_libs/revealjs/plugin/math/math.js"></script><script>window.define = window.backupDefine; window.backupDefine = undefined;</script><script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': true,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'fade',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script><script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script><script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
            const codeEl = trigger.previousElementSibling.cloneNode(true);
            for (const childEl of codeEl.children) {
              if (isCodeAnnotation(childEl)) {
                childEl.remove();
              }
            }
            return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp("https:\/\/sta199-f25\.github\.io\/");
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>


</body></html>