{
  "hash": "49d6d316d06e034fba1ea1781b789b75",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Exam 2 review\"\nsubtitle: \"Lecture 23\"\ndate: \"2025-11-18\"\nformat: \n  revealjs: \n    output-file: 23-exam-2-review-slides.html\n    footer: \"[🔗 sta199-f25.github.io](https://sta199-f25.github.io/)\"\n    theme: slides.scss\n    transition: fade\n    slide-number: true\n    logo: images/logo.png\n    pdf-separate-fragments: true\n    toc: false\n  html: \n    code-link: true\nfilters: \n  - ../remove-fmt-skip.lua\neditor_options: \n  chunk_output_type: console\n---\n\n\n\n# Warm-up\n\n## While you wait: Participate 📱💻 {.xsmall}\n\n::: columns\n\n::: {.column width=\"70%\"}\n\n::: wooclap\n\nWhat is sensitivity also known as?\n\n::: wooclap-choices\n- True positive rate\n- True negative rate\n- False positive rate\n- False negative rate\n- Recall\n:::\n\n:::\n\n:::\n\n::: {.column width=\"30%\"}\n![](images/wooclap-qr.png){width=\"200\" fig-align=\"center\"}\n\n::: small\nScan the QR code or go to [app.wooclap.com/sta199](https://app.wooclap.com/sta199). Log in with your Duke NetID.\n:::\n\n:::\n\n:::\n\n## Announcements\n\n- Cheat sheet: 8.5x11, both sides, hand written or typed, any content you want, must be prepared by you\n\n- Bring a pencil and eraser (you’re allowed to use a pen, but you might not want to)\n\n- Reminder: Academic dishonesty / Duke Community Standard\n\n## From last class: ae\\-14\\-chicago\\-taxi\\-classification {.smaller}\n\n::: appex\nFinish up the application exercise by finding the area under the ROC curve.\n:::\n\n## Recap {.xsmall}\n\n::: incremental\n- Split data into training and testing sets (generally 75/25)\n\n- Fit models on training data and reduce to a few candidate models\n\n- Make predictions on testing data\n\n- Evaluate predictions on testing data using appropriate predictive performance metrics\n  - Linear models: Adjusted R-squared, AIC, etc.\n  - Logistic models: False negative and positive rates, AUC (area under the curve), etc.\n\n- Don't forget to also consider explainability and domain knowledge when selecting a final model\n\n- In a future machine learning course: Cross-validation (partitioning training data into training and validation sets and repeating this many times to evaluate model predictive performance before using the testing data), feature engineering,  hyperparameter tuning, more complex models (random forests, gradient boosting machines, neural networks, etc.)\n:::\n\n# Modeling review\n\n## Hotel cancellations\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(tidymodels)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhotels <- read_csv(\"data/hotels.csv\")\n```\n:::\n\n\n\n\n## Data prep {.smaller}\n\n- Relevel `is_canceled`\n- Remove bookings with average daily rate greater than $1,000\n- Remove bookings with number of adults greater than or equal to 5\n- Split the data into a training set (75%) and a testing set (25%)\n\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"|2-5|6|1|8-11\"}\nhotels <- hotels |>\n  mutate(\n    is_canceled = if_else(is_canceled == 1, \"canceled\", \"not canceled\"),\n    is_canceled = fct_relevel(is_canceled, \"not canceled\", \"canceled\")\n  ) |>\n  filter(adr <= 1000, adults < 5)\n\nset.seed(1117)\nhotels_split <- initial_split(hotels)\nhotels_train <- training(hotels_split)\nhotels_test <- testing(hotels_split)\n```\n:::\n\n\n## Participate 📱💻 {.xsmall}\n\n::: columns\n\n::: {.column width=\"70%\"}\n\n::: wooclap\n\nWhat type of model would you use to answer the question:\n\n> Are reservations earlier in the month or later in the month more likely to be cancelled?\n\n::: wooclap-choices\n- Linear regression with a numerical predictor\n- Linear regression with a categorical predictor\n- Linear regression with a log-transformed outcome and a numerical predictor\n- Linear regression with a log-transformed outcome and a categorical predictor\n- Logistic regression with a numerical predictor\n- Logistic regression with a categorical predictor\n:::\n\n:::\n\n:::\n\n::: {.column width=\"30%\"}\n![](images/wooclap-qr.png){width=\"200\" fig-align=\"center\"}\n\n::: small\nScan the QR code or go to [app.wooclap.com/sta199](https://app.wooclap.com/sta199). Log in with your Duke NetID.\n:::\n\n:::\n\n:::\n\n## Linear regression\n\nNumerical outcome:\n\n$$\ny = \\beta_0 + \\beta_1 x_1 + \\beta_2 x_2 + \\cdots + \\beta_k x_k + \\varepsilon\n$$\n\n<br>\n\n$$\n\\widehat{y} = b_0 + b_1 x_1 + b_2 x_2 + \\cdots + b_k x_k\n$$\n\n## Linear regression with log-transformed outcome\n\nNumerical outcome, log-transformed for a better linear fit:\n\n$$\nlog(y) = \\beta_0 + \\beta_1 x_1 + \\beta_2 x_2 + \\cdots + \\beta_k x_k + \\varepsilon\n$$\n\n<br>\n\n$$\nlog(\\widehat{y}) = b_0 + b_1 x_1 + b_2 x_2 + \\cdots + b_k x_k\n$$\n\n## Logistic regression\n\nBinary outcome, where $p = P(Y=1)$, the probability of success:\n\n$$\n\\log\\left(\\frac{p}{1-p}\\right) = \\beta_0 + \\beta_1 x_1 + \\beta_2 x_2 + \\cdots + \\beta_k x_k + \\varepsilon\n$$\n\n<br>\n\n$$\n\\log\\left(\\frac{\\widehat{p}}{1-\\widehat{p}}\\right) = b_0 + b_1 x_1 + b_2 x_2 + \\cdots + b_k x_k\n$$\n\n## Cancellation ~ arrival date {.smaller}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nis_canceled_fit_1 <- logistic_reg() |>\n  fit(is_canceled ~ arrival_date_day_of_month, data = hotels_train)\n\ntidy(is_canceled_fit_1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 5\n  term                      estimate std.error statistic   p.value\n  <chr>                        <dbl>     <dbl>     <dbl>     <dbl>\n1 (Intercept)               -0.510    0.0142      -35.8  1.80e-280\n2 arrival_date_day_of_month -0.00152  0.000789     -1.93 5.41e-  2\n```\n\n\n:::\n:::\n\n\n## Slope in logistic regression {.smaller}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntidy(is_canceled_fit_1) |>\n  select(term, estimate) |>\n  mutate(exp_estimate = exp(estimate))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 3\n  term                      estimate exp_estimate\n  <chr>                        <dbl>        <dbl>\n1 (Intercept)               -0.510          0.601\n2 arrival_date_day_of_month -0.00152        0.998\n```\n\n\n:::\n:::\n\n\n. . .\n\n<br>\n\nFor each day the booking is later in the month, the odds of reservations being canceled is predicted to be lower by a factor of 0.998, on average.\n\n## Intercept in logistic regression {.smaller}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntidy(is_canceled_fit_1) |>\n  select(term, estimate) |>\n  mutate(exp_estimate = exp(estimate))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 3\n  term                      estimate exp_estimate\n  <chr>                        <dbl>        <dbl>\n1 (Intercept)               -0.510          0.601\n2 arrival_date_day_of_month -0.00152        0.998\n```\n\n\n:::\n:::\n\n\n. . .\n\n<br>\n\nOn the 0th day of the month, the odds of reservations being canceled is predicted to be 0.601, on average.\nThe intercept is not meaningful in this context since there is no 0th day of the month.\n\n## Prediction in logistic regression {.smaller}\n\n::: task\nPredict the probability of cancellation for a booking made on the 18th day of the month.\n:::\n\n. . .\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnew_booking <- tibble(arrival_date_day_of_month = 18)\naugment(is_canceled_fit_1, new_data = new_booking)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 4\n  .pred_class  `.pred_not canceled` .pred_canceled\n  <fct>                       <dbl>          <dbl>\n1 not canceled                0.631          0.369\n# ℹ 1 more variable: arrival_date_day_of_month <dbl>\n```\n\n\n:::\n:::\n\n\n## `augment()` vs. `predict()` {.smaller}\n\n- `augment()` returns the data frame passed to `new_data` _augment_ed by\n  - the predicted probability of success,\n  - the predicted probability of success, and\n  - the predicted class (based on a 0.5 cutoff by default)\n\n\n::: {.cell}\n\n```{.r .cell-code}\naugment(is_canceled_fit_1, new_data = new_booking)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 4\n  .pred_class  `.pred_not canceled` .pred_canceled\n  <fct>                       <dbl>          <dbl>\n1 not canceled                0.631          0.369\n# ℹ 1 more variable: arrival_date_day_of_month <dbl>\n```\n\n\n:::\n:::\n\n\n. . .\n\n- `predict()` the predicted class (based on a 0.5 cutoff by default)\n\n\n::: {.cell}\n\n```{.r .cell-code}\npredict(is_canceled_fit_1, new_data = new_booking)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 1\n  .pred_class \n  <fct>       \n1 not canceled\n```\n\n\n:::\n:::\n\n\n## Cancellation ~ arrival date + hotel type {.smaller}\n\n::: task\nFit another model to predict whether a reservation was cancelled from `arrival_date_day_of_month` and `hotel` type (Resort or City Hotel), allowing the relationship between `arrival_date_day_of_month` and `is_canceled` to **not** vary based on `hotel` type.\n:::\n\n. . .\n\n\n::: {.cell}\n\n```{.r .cell-code}\nis_canceled_fit_2 <- logistic_reg() |>\n  fit(is_canceled ~ arrival_date_day_of_month + hotel, data = hotels_train)\n\ntidy(is_canceled_fit_2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 5\n  term                      estimate std.error statistic  p.value\n  <chr>                        <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept)               -0.315    0.0151      -20.9  3.46e-97\n2 arrival_date_day_of_month -0.00155  0.000797     -1.94 5.18e- 2\n3 hotelResort Hotel         -0.614    0.0153      -40.0  0       \n```\n\n\n:::\n:::\n\n\n## Slope in logistic regression {.smaller}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntidy(is_canceled_fit_2) |>\n  select(term, estimate) |>\n  mutate(exp_estimate = exp(estimate))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 3\n  term                      estimate exp_estimate\n  <chr>                        <dbl>        <dbl>\n1 (Intercept)               -0.315          0.729\n2 arrival_date_day_of_month -0.00155        0.998\n3 hotelResort Hotel         -0.614          0.541\n```\n\n\n:::\n:::\n\n\n. . .\n\n<br>\n\nHolding hotel type constant, for each day the booking is later in the month, the odds of reservations being canceled is predicted to be lower by a factor of 0.998, on average.\n\n## Slope in logistic regression {.smaller}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntidy(is_canceled_fit_2) |>\n  select(term, estimate) |>\n  mutate(exp_estimate = exp(estimate))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 3\n  term                      estimate exp_estimate\n  <chr>                        <dbl>        <dbl>\n1 (Intercept)               -0.315          0.729\n2 arrival_date_day_of_month -0.00155        0.998\n3 hotelResort Hotel         -0.614          0.541\n```\n\n\n:::\n:::\n\n\n. . .\n\n<br>\n\nHolding arrival day of month constant, the odds of Resort Hotel reservations being canceled is predicted to be lower by a factor of 0.541 compared to City Hotel reservations, on average.\n\n## Intercept in logistic regression {.smaller}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntidy(is_canceled_fit_2) |>\n  select(term, estimate) |>\n  mutate(exp_estimate = exp(estimate))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 3\n  term                      estimate exp_estimate\n  <chr>                        <dbl>        <dbl>\n1 (Intercept)               -0.315          0.729\n2 arrival_date_day_of_month -0.00155        0.998\n3 hotelResort Hotel         -0.614          0.541\n```\n\n\n:::\n:::\n\n\n. . .\n\n<br>\n\nOn the 0th day of the month, the odds of City Hotel reservations being canceled is predicted to be 0.729, on average.\nThe intercept is not meaningful in this context since there is no 0th day of the month.\n\n## Cancellation ~ arrival date * hotel type {.smaller}\n\n::: task\nFit another model to predict whether a reservation was cancelled from `arrival_date_day_of_month` and `hotel` type (Resort or City Hotel), allowing the relationship between `arrival_date_day_of_month` and `is_canceled` to vary based on `hotel` type.\n:::\n\n. . .\n\n\n::: {.cell}\n\n```{.r .cell-code}\nis_canceled_fit_3 <- logistic_reg() |>\n  fit(is_canceled ~ arrival_date_day_of_month * hotel, data = hotels_train)\n\ntidy(is_canceled_fit_3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 5\n  term                           estimate std.error statistic  p.value\n  <chr>                             <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept)                    -0.321    0.0172     -18.7   6.73e-78\n2 arrival_date_day_of_month      -0.00117  0.000954    -1.23  2.19e- 1\n3 hotelResort Hotel              -0.594    0.0313     -19.0   3.50e-80\n4 arrival_date_day_of_month:hot… -0.00125  0.00174     -0.719 4.72e- 1\n```\n\n\n:::\n:::\n\n\n## Logistic regression w/ interaction effect {.smaller}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntidy(is_canceled_fit_3) |>\n  select(term, estimate)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 2\n  term                                        estimate\n  <chr>                                          <dbl>\n1 (Intercept)                                 -0.321  \n2 arrival_date_day_of_month                   -0.00117\n3 hotelResort Hotel                           -0.594  \n4 arrival_date_day_of_month:hotelResort Hotel -0.00125\n```\n\n\n:::\n:::\n\n\n<br>\n\n. . .\n\n$$\n\\begin{aligned}\n\\log\\left(\\frac{\\widehat{p}}{1-\\widehat{p}}\\right) &= -0.321 \\\\\n&- 0.00117 \\times \\texttt{arrival_date_day_of_month} \\\\\n&- 0.594 \\times \\texttt{hotelResort Hotel} \\\\\n&- 0.00125 \\times \\texttt{arrival_date_day_of_month:hotelResort Hotel} \\\\\n\\end{aligned}\n$$\n\n## Logistic regression w/ interaction effect {.smaller .scrollable}\n\n$$\n\\begin{aligned}\n\\log\\left(\\frac{\\widehat{p}}{1-\\widehat{p}}\\right) &= -0.321 \\\\\n&- 0.00117 \\times \\texttt{arrival_date_day_of_month} \\\\\n&- 0.594 \\times \\texttt{hotelResort Hotel} \\\\\n&- 0.00125 \\times \\texttt{arrival_date_day_of_month:hotelResort Hotel} \\\\\n\\end{aligned}\n$$\n\n<br>\n\n. . .\n\n**City Hotel:**\n\n$$\n\\begin{aligned}\n\\log\\left(\\frac{\\widehat{p}}{1-\\widehat{p}}\\right) &= -0.321 \\\\\n&- 0.00117 \\times \\texttt{arrival_date_day_of_month} \\\\\n&- 0.594 \\times 0 \\\\\n&- 0.00125 \\times \\texttt{arrival_date_day_of_month} \\times 0 \\\\\n\\\\\n&= -0.321 - 0.00117 \\times \\texttt{arrival_date_day_of_month} \\\\\n\\end{aligned}\n$$\n\n## Logistic regression w/ interaction effect {.smaller .scrollable}\n\n$$\n\\begin{aligned}\n\\log\\left(\\frac{\\widehat{p}}{1-\\widehat{p}}\\right) &= -0.321 \\\\\n&- 0.00117 \\times \\texttt{arrival_date_day_of_month} \\\\\n&- 0.594 \\times \\texttt{hotelResort Hotel} \\\\\n&- 0.00125 \\times \\texttt{arrival_date_day_of_month:hotelResort Hotel} \\\\\n\\end{aligned}\n$$\n\n<br>\n\n. . .\n\n**Resort Hotel:**\n\n$$\n\\begin{aligned}\n\\log\\left(\\frac{\\widehat{p}}{1-\\widehat{p}}\\right) &= -0.321 \\\\\n&- 0.00117 \\times \\texttt{arrival_date_day_of_month} \\\\\n&- 0.594 \\times 1 \\\\\n&- 0.00125 \\times \\texttt{arrival_date_day_of_month} \\times 1 \\\\\n\\\\\n&= -(0.321+0.594) - (0.00117+0.00125) \\times \\texttt{arrival_date_day_of_month} \\\\\n\\\\\n&= -0.915 - 0.00242 \\times \\texttt{arrival_date_day_of_month} \\\\\n\\end{aligned}\n$$\n\n## Logistic regression w/ interaction effect {.smaller}\n\n**City Hotel:**\n\n$$\n\\log\\left(\\frac{\\widehat{p}}{1-\\widehat{p}}\\right) = -0.321 - 0.00117 \\times \\texttt{arrival_date_day_of_month}\n$$\n\n- `exp(-0.00117)` = 0.999: In City Hotels, for each day the booking is later in the month, the odds of reservations being canceled is predicted to be lower by a factor of 0.999, on average.\n\n- `exp(−0.321)` = 0.725: In City Hotels, on the 0th day of the month, the odds of reservations being canceled is predicted to be 0.725, on average.\nThe intercept is not meaningful in this context since there is no 0th day of the month.\n\n## Logistic regression w/ interaction effect {.smaller}\n\n**Resort Hotel:**\n\n$$\n\\log\\left(\\frac{\\widehat{p}}{1-\\widehat{p}}\\right) = -0.915 - 0.00242 \\times \\texttt{arrival_date_day_of_month}\n$$\n\n- `exp(-0.00117)` = 0.998: In Resort Hotels, for each day the booking is later in the month, the odds of reservations being canceled is predicted to be lower by a factor of 0.998, on average.\n\n- `exp(−0.321)` = 0.401: In Resort Hotels, on the 0th day of the month, the odds of reservations being canceled is predicted to be 0.401, on average.\nThe intercept is not meaningful in this context since there is no 0th day of the month.\n\n## Participate 📱💻 {.xsmall}\n\n::: columns\n\n::: {.column width=\"70%\"}\n\n::: wooclap\n\nSuppose we want to select a final model to predict whether a reservation was cancelled. Which metric would be most appropriate to evaluate the predictive performance of our logistic regression models?\n\n::: wooclap-choices\n- True positive rate\n- Area under the ROC curve\n- Adjusted R-squared\n- Root mean squared error\n- R-squared\n:::\n\n:::\n\n:::\n\n::: {.column width=\"30%\"}\n![](images/wooclap-qr.png){width=\"200\" fig-align=\"center\"}\n\n::: small\nScan the QR code or go to [app.wooclap.com/sta199](https://app.wooclap.com/sta199). Log in with your Duke NetID.\n:::\n\n:::\n\n:::\n\n## Area under the ROC curve (AUC) {.xsmall}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nis_canceled_aug_1 <- augment(is_canceled_fit_1, new_data = hotels_test)\nis_canceled_aug_2 <- augment(is_canceled_fit_2, new_data = hotels_test)\nis_canceled_aug_3 <- augment(is_canceled_fit_3, new_data = hotels_test)\n```\n:::\n\n\n::: {.columns}\n\n::: {.column width=\"33%\" .fragment}\n\nSingle predictor:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nroc_auc(\n  is_canceled_aug_1,\n  truth = is_canceled,\n  .pred_canceled,\n  event_level = \"second\"\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n  .metric .estimator .estimate\n  <chr>   <chr>          <dbl>\n1 roc_auc binary         0.503\n```\n\n\n:::\n:::\n\n\n:::\n\n::: {.column width=\"33%\" .fragment}\n\nMain effects:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nroc_auc(\n  is_canceled_aug_2,\n  truth = is_canceled,\n  .pred_canceled,\n  event_level = \"second\"\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n  .metric .estimator .estimate\n  <chr>   <chr>          <dbl>\n1 roc_auc binary         0.571\n```\n\n\n:::\n:::\n\n\n:::\n\n::: {.column width=\"33%\" .fragment}\n\nInteraction effects:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nroc_auc(\n  is_canceled_aug_3,\n  truth = is_canceled,\n  .pred_canceled,\n  event_level = \"second\"\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n  .metric .estimator .estimate\n  <chr>   <chr>          <dbl>\n1 roc_auc binary         0.571\n```\n\n\n:::\n:::\n\n\n:::\n\n::: \n\n::: {.task .fragment}\nWhich model would you select as your final model based on AUC?\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}