---
title: "Improvement and progress II: project to polish"
subtitle: "Milestone 5"
categories: "Project"
execute:
  echo: false
---

::: callout-important
You must attend this lab in person and participate in the teamwork in person to be eligible for the points for this milestone.
Team members who are not in lab in person for this milestone will not be eligible for these points, regardless of their contribution throughout the rest of the project.
:::

By this point you've received feedback peer feedback on your project and you should be working on incorporating that feedback to improve your project and making further progress on it.
This milestone ensures you're keeping on task and doing these things.

# Goals

The goals of this milestone are as follows:

-   Incorporate feedback from your peers
-   Polish your project prior to your presentation and final write-up next week!

# Instructions

Make some progress, evidenced by commits to your repo since project milestone 4. 
These commits should

-   explicitly closing issues opened as peer feedback, and
-   make further progress on the project.

# Grading

This milestone will be graded for completion, not accuracy.
We will check to see if the team has made commits to their repo since project milestone 4 and closed all issues that were opened as part of proposal feedback.

-   0 points: No commits since project milestone 4

-   1 point: Only a single commit since project milestone 4, regardless of how many issues closed

-   2-4 points: More than 1 commit since project milestone 4 and but not all issues closed

-   5 points: More than 1 commit since project milestone 4 and all issues closed
