{
  "hash": "fe35c0326faac86e526dcbaf46e39ed6",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"AE 10: Ice cover in Madison, WI area lakes\"\nsubtitle: \"Suggested answers\"\ncategories: \n  - Application exercise\n  - Answers\n---\n\n::: callout-important\nThese are suggested answers.\nThis document should be used as reference only, it's not designed to be an exhaustive key.\n:::\n\nThe data for this application exercise comes from the [lterdatasampler](https://lter.github.io/lterdatasampler/) package. The mission of the [Long Term Ecological Research program (LTER)](https://lternet.edu) Network is to \"provide the scientific community, policy makers, and society with the knowledge and predictive understanding necessary to conserve, protect, and manage the nation’s ecosystems, their biodiversity, and the services they provide.\"\n\nSpecifically we'll be using data from the North Temperate Lakes LTER (NTL-LTER) site, which is located in the Madison, WI area, modeling the relationship between number of days that a lake is frozen, excluding periods where the lake thaws before refreezing again, and annual average temperature.\n\n## Getting started\n\n### Packages\n\nWe will use the **tidyverse** package for data visualization and wrangling and the **tidymodels** package for modeling.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(tidymodels)\n```\n:::\n\n\n### Data\n\nThe data can be found in the `data` folder; it's called `icecover.csv`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nicecover <- read_csv(\"data/icecover.csv\")\n```\n:::\n\n\nThe data dictionary is below:\n\n| Variable Name      | Description                                                      |\n|:-------------------|:-----------------------------------------------------------------|\n| `lakeid`           | Lake name                                                        |\n| `ice_on`           | Date of freeze of lake                                           |\n| `ice_off`          | Date of ice breakup of lake                                      |\n| `ice_duration`     | Number of days between the freeze and breakup dates of each lake |\n| `year`             | Year of observation                                              |\n| `annual_avg_temp`  | Annual average air temperature (°C)                              |\n\n## Visualizing the model\n\nWe’re going to investigate the relationship between `ice_duration` and `annual_avg_temp`.\n\n- Create an appropriate plot to investigate this relationship. Add appropriate labels to the plot.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(icecover, aes(x = annual_avg_temp, y = ice_duration)) +\n  geom_point() +\n  labs(\n    x = \"Annual average temperature (°C)\",\n    y = \"Ice duration (days)\",\n    title = \"Ice duration vs. annual average temperature\",\n    subtitle = \"North Temperate Lakes LTER\"\n  )\n```\n\n::: {.cell-output-display}\n![](ae-10-icecover-model-A_files/figure-html/visualize-1.png){width=672}\n:::\n:::\n\n\n- If you were to draw a a straight line to best represent the relationship between ice duration and annual average temperature, where would it go? Why?\n\n*Start from the top left and go towards bottom right. Identify the first and last point and draw a line through most the others.*\n\n- Now, let R draw the line for you. Refer to the documentation at <https://ggplot2.tidyverse.org/reference/geom_smooth.html>. Specifically, refer to the method section.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(icecover, aes(x = annual_avg_temp, y = ice_duration)) +\n  geom_point() +\n  geom_smooth(method = \"lm\") +\n  labs(\n    x = \"Annual average temperature (°C)\",\n    y = \"Ice duration (days)\",\n    title = \"Ice duration vs. annual average temperature\",\n    subtitle = \"North Temperate Lakes LTER\"\n  )\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](ae-10-icecover-model-A_files/figure-html/visualize-with-line-1.png){width=672}\n:::\n:::\n\n\n- What types of questions can this plot help answer?\n\n*How does ice duration change with annual average temperature? What is the predicted ice duration for a given annual average temperature?*\n\n- We can use this line to make predictions. Predict what you think the ice duration would be in a year with annual average temperature of 7, 10, and 12 °C. Which prediction is considered extrapolation?\n\n*At 7 °C, we estimate ice duration to be 100 days. At 10 °C, we estimate ice duration to be 80 days. 12 °C would be considered extrapolation.*\n\n- What is a residual?\n\n*Difference between predicted and observed.*\n\n## Model fitting\n\nFit a model to predict ice cover from average annual temperature.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nice_temp_fit <- linear_reg() |>\n  fit(ice_duration ~ annual_avg_temp, data = icecover)\n\nice_temp_fit\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nparsnip model object\n\n\nCall:\nstats::lm(formula = ice_duration ~ annual_avg_temp, data = data)\n\nCoefficients:\n    (Intercept)  annual_avg_temp  \n        148.110           -6.182  \n```\n\n\n:::\n:::\n\n\n## Model summary\n\n- Display the model summary including estimates for the slope and intercept along with measurements of uncertainty around them. Show how you can extract these values from the model output.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntidy(ice_temp_fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 5\n  term            estimate std.error statistic  p.value\n  <chr>              <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept)       148.        7.77     19.1  1.38e-53\n2 annual_avg_temp    -6.18      1.01     -6.10 3.31e- 9\n```\n\n\n:::\n:::\n\n\n- Write out your model using mathematical notation.\n\n$$ \\widehat{ice~duration} = 148 - 6.18 \\times annual~avg~temp $$\n\n## Correlation\n\nWe can also assess correlation between two quantitative variables.\n\n- What is correlation? What are values correlation can take?\n\n*Strength and direction of a linear relationship. It’s bounded by -1 and 1.*\n\n- What is the correlation between heights and weights of fish?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nicecover |>\n  summarize(r = cor(ice_duration, annual_avg_temp))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 1\n       r\n   <dbl>\n1 -0.332\n```\n\n\n:::\n:::\n\n\n## Fitting other models\n\nWe can fit more models than just a straight line. Change the plotting code from earlier to use `method = \"loess\"`. What is different from the plot created before?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(icecover, aes(x = annual_avg_temp, y = ice_duration)) +\n  geom_point() +\n  geom_smooth(method = \"loess\") +\n  labs(\n    x = \"Annual average temperature (°C)\",\n    y = \"Ice duration (days)\",\n    title = \"Ice duration vs. annual average temperature\",\n    subtitle = \"North Temperate Lakes LTER\"\n  )\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](ae-10-icecover-model-A_files/figure-html/visualize-with-curve-1.png){width=672}\n:::\n:::\n\n",
    "supporting": [
      "ae-10-icecover-model-A_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}