{
  "hash": "ce74fe1f201747ec489639040888d94c",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Quantifying uncertainty\"\nsubtitle: \"Lecture 24\"\ndate: \"2025-11-25\"\nformat: \n  revealjs: \n    output-file: 24-quantifying-uncertainty-slides.html\n    footer: \"[🔗 sta199-f25.github.io](https://sta199-f25.github.io/)\"\n    theme: slides.scss\n    transition: fade\n    slide-number: true\n    logo: images/logo.png\n    pdf-separate-fragments: true\n    toc: false\n  html: \n    code-link: true\nfilters: \n  - ../remove-fmt-skip.lua\neditor_options: \n  chunk_output_type: console\n---\n\n\n\n# Warm-up\n\n## While you wait: Participate 📱💻 {.xsmall}\n\n::: columns\n\n::: {.column width=\"70%\"}\n\n::: wooclap\n\nGiven that HW 6 will be assigned on Monday, Dec 1, what day should HW 5 be due? It will be due at 11:59 pm on the deadline we decide on.\n\n::: wooclap-choices\n- Sunday, Nov 30 - no change\n- Monday, Dec 1 - postponed by 1 day\n- Tuesday, Dec 2 - postponed by 2 days\n- Wednesday, Dec 3 - postponed by 3 days\n:::\n\n:::\n\n:::\n\n::: {.column width=\"30%\"}\n![](images/wooclap-qr.png){width=\"200\" fig-align=\"center\"}\n\n::: small\nScan the QR code or go to [app.wooclap.com/sta199](https://app.wooclap.com/sta199). Log in with your Duke NetID.\n:::\n\n:::\n\n:::\n\n\n## Announcements {.xsmall}\n\n- HW:\n  - HW 5 due [whichever date we decided on in the previous slide]\n  - HW 6 due at 11:59 pm on Fri, Dec 6, but will be accepted until Sun, Dec 7 at 11:59 pm without penalty\n\n- Final exam:\n  - In-class only, \"cheat sheet\" with same specs as usual allowed\n  - Cumulative -- will definitely have material since Exam 2, but there's so little of it that it won't be a huge portion of the exam\n  - Final exam review during reading period -- date/time/location TBA\n  - Office hours during reading period + final exam week -- schedule TBA\n\n- Grades:\n  - Exam 2 in-class grades posted -- can review questions in my office hours anytime before the final\n  - Exam 2 take-home + project grades to be posted after Thanksgiving break\n\n# Quantifying uncertainty\n\n## Goal\n\nFind range of plausible values for the slope using bootstrap confidence intervals.\n\n## Packages\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# load packages\nlibrary(tidyverse) # for data wrangling and visualization\nlibrary(tidymodels) # for modeling\nlibrary(openintro) # for Duke Forest dataset\nlibrary(scales) # for pretty axis labels\nlibrary(glue) # for constructing character strings\nlibrary(knitr) # for neatly formatted tables\n```\n:::\n\n\n## Data: Houses in Duke Forest {.smaller}\n\n::::: columns\n::: {.column width=\"50%\"}\n-   Data on houses that were sold in the Duke Forest neighborhood of Durham, NC around November 2020\n-   Scraped from Zillow\n-   Source: [`openintro::duke_forest`](http://openintrostat.github.io/openintro/reference/duke_forest.html)\n:::\n\n::: {.column width=\"50%\"}\n![](images/24/duke_forest_home.jpg){fig-alt=\"Home in Duke Forest\"}\n:::\n:::::\n\n**Goal**: Use the area (in square feet) to understand variability in the price of houses in Duke Forest.\n\n## Exploratory data analysis\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nggplot(duke_forest, aes(x = area, y = price)) +\n  geom_point(alpha = 0.7) +\n  labs(\n    x = \"Area (square feet)\",\n    y = \"Sale price (USD)\",\n    title = \"Price and area of houses in Duke Forest\"\n  ) +\n  scale_y_continuous(labels = label_dollar())\n```\n\n::: {.cell-output-display}\n![](24-quantifying-uncertainty_files/figure-html/unnamed-chunk-1-1.png){width=672}\n:::\n:::\n\n\n## Modeling {.smaller}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_fit <- linear_reg() |>\n  fit(price ~ area, data = duke_forest)\n\ntidy(df_fit) |>\n  kable(digits = 2) # neatly format table to 2 digits\n```\n\n::: {.cell-output-display}\n\n\n|term        |  estimate| std.error| statistic| p.value|\n|:-----------|---------:|---------:|---------:|-------:|\n|(Intercept) | 116652.33|  53302.46|      2.19|    0.03|\n|area        |    159.48|     18.17|      8.78|    0.00|\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n## Participate 📱💻 {.xsmall}\n\n::: columns\n\n::: {.column width=\"70%\"}\n\n::: wooclap\n\nWhich of the following is the correct interpretation of the **intercept**?\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|term        | estimate| std.error| statistic| p.value|\n|:-----------|--------:|---------:|---------:|-------:|\n|(Intercept) |   116652|     53302|         2|       0|\n|area        |      159|        18|         9|       0|\n\n\n:::\n:::\n\n\n::: {.wooclap-choices .small}\n- For each additional square foot, the model predicts the sale price of Duke Forest houses to be higher by $116,652, on average.\n- Duke Forest houses that are 0 square feet are predicted to sell, for $116,652, on average.\n- For each additional square foot, the model predicts the sale price of Duke Forest houses to be lower by $15,900, on average.\n- Duke Forest houses that are 0 square feet are predicted to sell, for $15,900, on average.\n:::\n\n:::\n\n:::\n\n::: {.column width=\"30%\"}\n![](images/wooclap-qr.png){width=\"200\" fig-align=\"center\"}\n\n::: small\nScan the QR code or go to [app.wooclap.com/sta199](https://app.wooclap.com/sta199). Log in with your Duke NetID.\n:::\n\n:::\n\n:::\n\n## Participate 📱💻 {.xsmall}\n\n::: columns\n\n::: {.column width=\"70%\"}\n\n::: wooclap\n\nWhich of the following is the correct interpretation of the **slope**?\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|term        | estimate| std.error| statistic| p.value|\n|:-----------|--------:|---------:|---------:|-------:|\n|(Intercept) |   116652|     53302|         2|       0|\n|area        |      159|        18|         9|       0|\n\n\n:::\n:::\n\n\n::: {.wooclap-choices .small}\n- For each additional square foot, the model predicts the sale price of Duke Forest houses to be higher by $159, on average.\n- Duke Forest houses that are 0 square feet are predicted to sell, for $116,652, on average.\n- For each additional square foot, the model predicts the sale price of Duke Forest houses to be lower by $15,900, on average.\n- Duke Forest houses that are 0 square feet are predicted to sell, for $159, on average.\n:::\n\n:::\n\n:::\n\n::: {.column width=\"30%\"}\n![](images/wooclap-qr.png){width=\"200\" fig-align=\"center\"}\n\n::: small\nScan the QR code or go to [app.wooclap.com/sta199](https://app.wooclap.com/sta199). Log in with your Duke NetID.\n:::\n\n:::\n\n:::\n\n## From sample to population {.smaller}\n\n> For each additional square foot, we expect the sale price of Duke Forest houses to be higher by $159, on average.\n\n<br>\n\n-   This estimate is valid for the single sample of 98 houses.\n-   But what if we're not interested quantifying the relationship between the size and price of a house in this single sample?\n-   What if we want to say something about the relationship between these variables for all houses in Duke Forest?\n\n## Statistical inference {.smaller}\n\n-   **Statistical inference** provide methods and tools so we can use the single observed sample to make valid statements (inferences) about the population it comes from\n\n-   For our inferences to be valid, the sample should be random and representative of the population we're interested in\n\n![](images/24/soup.png){fig-alt=\"Soup in a bowl\"}\n\n## Inference for simple linear regression\n\n-   Calculate a confidence interval for the slope, $\\beta_1$ (today)\n\n-   Conduct a hypothesis test for the slope,$\\beta_1$ (next week)\n\n# Confidence interval for the slope\n\n## Confidence interval {.smaller}\n\n::: incremental\n-   A plausible range of values for a population parameter is called a **confidence interval**\n-   Using only a single point estimate is like fishing in a murky lake with a spear, and using a confidence interval is like fishing with a net\n    -   We can throw a spear where we saw a fish but we will probably miss, if we toss a net in that area, we have a good chance of catching the fish\n    -   Similarly, if we report a point estimate, we probably will not hit the exact population parameter, but if we report a range of plausible values we have a good shot at capturing the parameter\n:::\n\n## Confidence interval for the slope {.smaller}\n\nA confidence interval will allow us to make a statement like \"*For each additional square foot, the model predicts the sale price of Duke Forest houses to be higher, on average, by $159, plus or minus X dollars.*\"\n\n. . .\n\n-   Should X be \\$10?\n    \\$100?\n    \\$1000?\n\n-   If we were to take another sample of 98 would we expect the slope calculated based on that sample to be exactly $159?\n    Off by \\$10?\n    \\$100?\n    \\$1000?\n\n-   The answer depends on how variable (from one sample to another sample) the sample statistic (the slope) is\n\n-   We need a way to quantify the variability of the sample statistic\n\n## Quantify the variability of the slope {.smaller}\n\n**for estimation**\n\n::: incremental\n-   Two approaches:\n    1.  Via simulation (what we'll do in this course)\n    2.  Via mathematical models (what you can learn about in future courses)\n-   **Bootstrapping** to quantify the variability of the slope for the purpose of estimation:\n    -   Bootstrap new samples from the original sample\n    -   Fit models to each of the samples and estimate the slope\n    -   Use features of the distribution of the bootstrapped slopes to construct a confidence interval\n:::\n\n\n::: {.cell}\n\n:::\n\n\n## Bootstrap sample 1\n\n::::: columns\n::: {.column width=\"50%\"}\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](24-quantifying-uncertainty_files/figure-html/unnamed-chunk-7-1.png){width=100%}\n:::\n:::\n\n\n:::\n\n::: {.column width=\"50%\"}\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](24-quantifying-uncertainty_files/figure-html/unnamed-chunk-8-1.png){width=100%}\n:::\n:::\n\n\n:::\n:::::\n\n## Bootstrap sample 2\n\n::::: columns\n::: {.column width=\"50%\"}\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](24-quantifying-uncertainty_files/figure-html/unnamed-chunk-9-1.png){width=100%}\n:::\n:::\n\n\n:::\n\n::: {.column width=\"50%\"}\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](24-quantifying-uncertainty_files/figure-html/unnamed-chunk-10-1.png){width=100%}\n:::\n:::\n\n\n:::\n:::::\n\n## Bootstrap sample 3\n\n::::: columns\n::: {.column width=\"50%\"}\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](24-quantifying-uncertainty_files/figure-html/unnamed-chunk-11-1.png){width=100%}\n:::\n:::\n\n\n:::\n\n::: {.column width=\"50%\"}\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](24-quantifying-uncertainty_files/figure-html/unnamed-chunk-12-1.png){width=100%}\n:::\n:::\n\n\n:::\n:::::\n\n## Bootstrap sample 4\n\n::::: columns\n::: {.column width=\"50%\"}\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](24-quantifying-uncertainty_files/figure-html/unnamed-chunk-13-1.png){width=100%}\n:::\n:::\n\n\n:::\n\n::: {.column width=\"50%\"}\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](24-quantifying-uncertainty_files/figure-html/unnamed-chunk-14-1.png){width=100%}\n:::\n:::\n\n\n:::\n:::::\n\n## Bootstrap sample 5\n\n::::: columns\n::: {.column width=\"50%\"}\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](24-quantifying-uncertainty_files/figure-html/unnamed-chunk-15-1.png){width=100%}\n:::\n:::\n\n\n:::\n\n::: {.column width=\"50%\"}\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](24-quantifying-uncertainty_files/figure-html/unnamed-chunk-16-1.png){width=100%}\n:::\n:::\n\n\n:::\n:::::\n\n. . .\n\n*so on and so forth...*\n\n## Bootstrap samples 1 - 5\n\n::::: columns\n::: {.column width=\"50%\"}\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](24-quantifying-uncertainty_files/figure-html/unnamed-chunk-17-1.png){width=100%}\n:::\n:::\n\n\n:::\n\n::: {.column width=\"50%\"}\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](24-quantifying-uncertainty_files/figure-html/unnamed-chunk-18-1.png){width=100%}\n:::\n:::\n\n\n:::\n:::::\n\n## Bootstrap samples 1 - 100\n\n\n::: {.cell}\n\n:::\n\n\n::::: columns\n::: {.column width=\"50%\"}\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](24-quantifying-uncertainty_files/figure-html/unnamed-chunk-20-1.png){width=100%}\n:::\n:::\n\n\n:::\n\n::: {.column width=\"50%\"}\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](24-quantifying-uncertainty_files/figure-html/unnamed-chunk-21-1.png){width=100%}\n:::\n:::\n\n\n:::\n:::::\n\n. . .\n\n::: question\nLook familiar?\n:::\n\n## Look familiar?\n\n::::: columns\n::: {.column width=\"50%\"}\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](24-quantifying-uncertainty_files/figure-html/unnamed-chunk-22-1.png){width=672}\n:::\n:::\n\n\n:::\n\n::: {.column width=\"50%\"}\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](24-quantifying-uncertainty_files/figure-html/unnamed-chunk-23-1.png){width=672}\n:::\n:::\n\n\n:::\n:::::\n\n\n\n## Slopes of bootstrap samples {.smaller}\n\n::: task\n**Fill in the blank:** For each additional square foot, the model predicts the sale price of Duke Forest houses to be higher, on average, by $159, plus or minus \\_\\_\\_ dollars.\n:::\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](24-quantifying-uncertainty_files/figure-html/unnamed-chunk-24-1.png){width=672}\n:::\n:::\n\n\n## Slopes of bootstrap samples {.smaller}\n\n::: task\n**Fill in the blank:** For each additional square foot, we expect the sale price of Duke Forest houses to be higher, on average, by $159, plus or minus \\_\\_\\_ dollars.\n:::\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](24-quantifying-uncertainty_files/figure-html/unnamed-chunk-25-1.png){width=672}\n:::\n:::\n\n\n## Confidence level {.smaller}\n\n::: task\nHow confident are you that the true slope is between \\$0 and \\$250?\nHow about \\$150 and \\$170?\nHow about \\$90 and \\$210?\n:::\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](24-quantifying-uncertainty_files/figure-html/unnamed-chunk-26-1.png){width=672}\n:::\n:::\n\n\n## 95% confidence interval {.smaller}\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](24-quantifying-uncertainty_files/figure-html/unnamed-chunk-27-1.png){width=672}\n:::\n:::\n\n\n::: incremental\n-   A 95% confidence interval is bounded by the middle 95% of the bootstrap distribution\n-   We are 95% confident that for each additional square foot, the model predicts the sale price of Duke Forest houses to be higher, on average, by $90.43 to $205.77.\n:::\n\n# Application exercise\n\n## ae\\-15\\-duke\\-forest\\-bootstrap {.smaller}\n\n::: appex\n-   Go to your ae project in RStudio.\n\n-   If you haven't yet done so, make sure all of your changes up to this point are committed and pushed, i.e., there's nothing left in your Git pane.\n\n-   If you haven't yet done so, click Pull to get today's application exercise file: *ae\\-15\\-duke\\-forest\\-bootstrap\\.qmd*.\n\n-   Work through the application exercise in class, and render, commit, and push your edits.\n:::\n",
    "supporting": [
      "24-quantifying-uncertainty_files/figure-html"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}