{
  "hash": "e6a2b82e7d98bbdda78296f85dcd975d",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Looking further\"\nsubtitle: \"Lecture 26\"\ndate: \"2025-12-04\"\nformat: \n  revealjs: \n    output-file: 26-looking-further-slides.html\n    footer: \"[🔗 sta199-f25.github.io](https://sta199-f25.github.io/)\"\n    theme: slides.scss\n    transition: fade\n    slide-number: true\n    logo: images/logo.png\n    pdf-separate-fragments: true\n    toc: false\n  html: \n    code-link: true\nfilters: \n  - ../remove-fmt-skip.lua\neditor_options: \n  chunk_output_type: console\n---\n\n\n\n# Warm-up\n\n## Give feedback!\n\n::: {.columns}\n\n::: {.column width=\"30%\".xsmall}\n\n-  Take 2 minutes to fill out the TA evaluation form -- link in your email! Due Monday, December 8th.\n\n-  Nominate a TA for the StatSci TA of the Year award by sending an email to <dus@stat.duke.edu> with a brief narrative for your nomination.\n\n:::\n\n::: {.column width=\"70%\"}\n\n![](images/25/ta-1.png){width=\"200px\"} ![](images/25/ta-2.png){width=\"200px\"} ![](images/25/ta-3.png){width=\"200px\"}\n\n:::\n\n::: \n\n::: xsmall\n-  Please also fill out the course evaluation (on DukeHub) as well, I'd love to your feedback!\n:::\n\n## Announcements {.xsmall}\n\n- HW 6:\n  - Q4: Instructions clarified -- save result as `births14`\n  - Q8: Table to recreate updated\n\n- Final exam review: Tuesday, Dec 9, 3-4 pm at Soc Sci 136\n\n- Final exam office hourse [posted](https://docs.google.com/spreadsheets/d/1rVx9uZVNcrG_nUSDo7iol5VEeGcHURASVtBpwZjz5bc/edit?usp=sharing)\n\n# From last time\n\n## Participate 📱💻 {.xsmall}\n\n::: columns\n\n::: {.column width=\"70%\"}\n\n::: wooclap\n\np-value is the probability of ___\n\n::: wooclap-choices\n- accepting the null hypothsesis\n- null hypothesis being true\n- observed or more extreme outcome given that the null hypothesis is true\n- null hypothesis being true given the outcome\n- a false positive\n:::\n\n:::\n\n:::\n\n::: {.column width=\"30%\"}\n![](images/wooclap-qr.png){width=\"200\" fig-align=\"center\"}\n\n::: small\nScan the QR code or go to [app.wooclap.com/sta199](https://app.wooclap.com/sta199). Log in with your Duke NetID.\n:::\n\n:::\n\n:::\n\n# Decision making with hypothesis tests\n\n## Setup\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(tidymodels)\nlibrary(openintro)\nlibrary(janitor)\n```\n:::\n\n\n## Sex discrimination in hiring {.smaller}\n\n- A study investigating sex discrimination in the 1970s was set in the context of personnel decisions within a bank. The research question we hope to answer is, “Are individuals who identify as female discriminated against in promotion decisions made by their managers who identify as male?” \n\n- This study considered sex roles, and only allowed for options of “male” and “female”. The identities being considered are not gender identities and the study allowed only for a binary classification of sex.\n\n::: aside\nRosen, B., and T. H. Jerdee. 1974. “Influence of Sex Role Stereotypes on Personnel Decisions.” Journal of Applied Psychology 59 (1): 9. <https://doi.org/doi.org/10.1037/h0035834>.\n:::\n\n## Study design {.smaller}\n\n- Participants: 48 bank supervisors who identified as male, attending a management institute at the University of North Carolina in 1972\n\n- Task: Assume the role of the personnel director of a bank and judge whether a candidate should be promoted to a branch manager position based on personnel files they were randomly assigned\n\n- Personnel files: Identical except that half of them indicated the candidate identified as male and the other half indicated the candidate identified as female\n\n- Variables: `sex` (male or female), `decision` (promoted or not promoted)\n\n## Participate 📱💻 {.xsmall}\n\n::: columns\n\n::: {.column width=\"70%\"}\n\n::: wooclap\n\nWhich of the following is the correct null hypothesis for this study?\n\n::: wooclap-choices\n- Sex and promotion decision are independent\n- Sex and promotion decision are dependent\n- Males are more likely to be promoted\n- Females are more likely to be promoted\n- Males and females are equally likely to be promoted\n:::\n\n:::\n\n:::\n\n::: {.column width=\"30%\"}\n![](images/wooclap-qr.png){width=\"200\" fig-align=\"center\"}\n\n::: small\nScan the QR code or go to [app.wooclap.com/sta199](https://app.wooclap.com/sta199). Log in with your Duke NetID.\n:::\n\n:::\n\n:::\n\n## Participate 📱💻 {.xsmall}\n\n::: columns\n\n::: {.column width=\"70%\"}\n\n::: wooclap\n\nWhich of the following is the correct alternative hypothesis for this study?\n\n::: wooclap-choices\n- Males are more likely to be promoted\n- Females are more likely to be promoted\n- Males and females are equally likely to be promoted\n- Males and females are not equally likely to be promoted\n:::\n\n:::\n\n:::\n\n::: {.column width=\"30%\"}\n![](images/wooclap-qr.png){width=\"200\" fig-align=\"center\"}\n\n::: small\nScan the QR code or go to [app.wooclap.com/sta199](https://app.wooclap.com/sta199). Log in with your Duke NetID.\n:::\n\n:::\n\n:::\n\n## Hypotheses {.smaller}\n\np = Proportion of candidates promoted\n\n<br>\n\n. . .\n\n**Null hypothesis:** Sex and promotion decision are independent, i.e., males and females are equally likely to be promoted.\n\n$$ p_{Male} = p_{Female} $$\n\n. . .\n\n**Alternative hypothesis:** Sex and promotion decision are dependent, i.e., males and females are not equally likely to be promoted.\n\n$$ p_{Male} \\ne p_{Female} $$\n\n\n## Data\n\n::: {.columns}\n\n::: {.column width=\"75%\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsex_discrimination |>\n  count(decision, sex) |>\n  pivot_wider(\n    names_from = decision,\n    values_from = n\n  ) |>\n  mutate(\n    total = promoted + `not promoted`,\n    p_prmtd = promoted / total\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 5\n  sex    promoted `not promoted` total p_prmtd\n  <fct>     <int>          <int> <int>   <dbl>\n1 male         21              3    24   0.875\n2 female       14             10    24   0.583\n```\n\n\n:::\n:::\n\n\n:::\n\n::: {.column width=\"25%\" .fragment .small}\n\n<br><br><br><br><br>\n\nObserved difference in promotion rates\n\n(male - female)\n\n= 0.875 - 0.583\n\n= 0.292\n\n:::\n\n::: \n\n## Simulating under the null\n\n![](images/26/sex-rand-shuffle-sort.png)\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}